truths = [
    "What is your biggest fear?",
    "What is your favorite childhood memory?",
    "What is the most embarrassing thing that has happened to you?",
    "Have you ever told a lie to get out of trouble? What was it?",
    "If you could switch lives with someone for a day, who would it be and why?",
    "What is your dream job?",
    "What is something you've always wanted to try but haven't had the chance to do yet?",
    "What is your favorite hobby or pastime?",
    "Have you ever had a crush on someone in this group?",
    "What is your most prized possession and why?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What is the most spontaneous thing you've ever done?",
    "Do you have any hidden talents?",
    "What is one thing you wish you could change about yourself?",
    "Have you ever had a near-death experience?",
    "If you could time travel, where and when would you go?",
    "What is your favorite book/movie and why?",
    "Have you ever broken a bone?",
    "What's the weirdest dream you've ever had?",
    "What is your biggest regret in life?",
    "Do you believe in ghosts or supernatural phenomena?",
    "If you could have one superpower, what would it be and why?",
    "What is something that always makes you smile?",
    "Have you ever been in love? If yes, tell us about it.",
    "What's the best gift you've ever received?",
    "What's the most adventurous thing you've ever done?",
    "What's your favorite season, and why?",
    "What's your favorite song, and what does it mean to you?",
    "Have you ever had a crush on a fictional character? If so, who?",
    "What's the most interesting place you've ever been to?",
    "Have you ever done something kind for a stranger?",
    "What's your favorite way to relax and de-stress?",
    "Do you have any pet peeves?",
    "If you could meet any historical figure, who would it be and why?",
    "What is your biggest pet peeve?",
    "Do you believe in fate or free will?",
    "What's the most courageous thing you've ever done?",
    "If you could live in any fictional world, which one would it be and why?",
    "What's your favorite way to give back to the community?",
    "If you could be any animal, which one would you choose and why?",
    "What's your most embarrassing nickname?",
    "Have you ever had a celebrity crush? Who was it?",
    "What's the scariest thing you've ever experienced?",
    "If you could erase one memory from your mind, what would it be?",
    "What's the best compliment you've ever received?",
    "Do you believe in karma?",
    "What's your favorite holiday and why?",
    "Have you ever pulled a prank on someone? What was it?",
    "What's your favorite type of cuisine?",
    "If you could be friends with any fictional character, who would it be and why?",
    "What's your favorite childhood cartoon or TV show?",
    "What's your favorite board game or video game?",
    "Have you ever had a near-death experience?",
    "What's your most embarrassing moment in front of a crush?",
    "If you could switch lives with someone for a day, who would it be and why?",
    "Have you ever cried during a movie? Which one?",
    "What's your favorite quote and why does it resonate with you?",
    "Do you believe in love at first sight?",
    "What's the most challenging thing you've ever accomplished?",
    "Have you ever met someone famous? Who was it and what happened?",
    "What's your favorite outdoor activity?",
    "Do you have any hidden talents?",
    "If you could be a character from a book or movie, who would you be and why?",
    "What's your dream travel destination?",
    "Have you ever done something illegal (even unintentionally)?",
    "What's your favorite memory with your best friend?",
    "Do you believe in second chances?",
    "What's the biggest lie you've ever told someone?",
    "What's the most spontaneous trip you've ever taken?",
    "If you could have any career, regardless of education or money, what would it be?",
    "What's the most interesting fact you know?",
    "What's your favorite way to spend a lazy day?",
    "Have you ever experienced deja vu? What was it like?",
    "If you could live in any era of history, which one would you choose and why?",
    "What's your favorite memory with your family?",
    "Do you have any phobias?",
    "What's your favorite childhood toy?",
    "Have you ever had a paranormal experience?",
    "If you could have any animal as a pet, what would you choose and why?",
    "What's the most embarrassing thing your parents have caught you doing?",
    "What's the best advice you've ever received from your parents or guardians?",
    "If you could learn any new skill instantly, what would it be?",
    "Have you ever won an award or trophy? What was it for?",
    "What's the most challenging thing about being your current age?",
    "If you could change one thing about the world, what would it be?",
    "What's the most significant life lesson you've learned so far?",
    "Have you ever had a dream that later came true?",
    "What's the most thoughtful gift you've ever given someone?",
    "If you could have any fictional creature as a pet, what would it be?",
    "What's the most meaningful compliment you've ever received?",
    "If you could master any instrument, which one would you choose and why?",
    "What's the best piece of advice you would give your younger self?",
    "What's the most adventurous thing you've ever eaten?",
    "Do you have a favorite family recipe?",
    "What's the most beautiful place you've ever visited?",
    "If you could have any historical figure as a mentor, who would it be and why?",
    "What's your favorite memory from school?",
    "Have you ever been in a car accident? What happened?",
    "What's your favorite thing to do when you're alone?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most memorable birthday celebration you've ever had?",
    "What's your favorite way to give back to the community?",
    "If you could time travel, which historical event would you like to witness?",
    "What's the most meaningful gift you've ever received?",
    "Do you believe in soulmates?",
    "If you could learn any language fluently, which one would you choose and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
    "Have you ever saved someone's life or been saved by someone?",
    "What's the most valuable lesson you've learned from a mistake?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the most exciting adventure you've ever been on?",
    "Do you have a favorite inspirational book or movie?",
    "If you could have any career without worrying about money, what would it be?",
    "What's the best piece of advice you've ever received from a friend?",
    "What's your favorite form of self-expression (writing, painting, etc.)?",
    "If you could have any animal's abilities, which animal would you choose and why?",
    "What's the most memorable dream you've ever had?",
    "If you could witness any event from history, what would it be and why?",
    "What's your favorite thing about yourself?",
    "Have you ever experienced a coincidence that seemed too strange to be true?",
    "What's your favorite way to relax and unwind after a long day?",
    "If you could invent something, what would it be and why?",
    "What's the most incredible act of kindness you've ever witnessed?",
    "Do you have any recurring dreams or nightmares?",
    "If you could go on a road trip anywhere, where would you go and who would you take?",
    "What's the most courageous thing you've ever done for someone else?",
    "If you could live in any fictional universe, which one would it be and why?",
    "What's your favorite way to spend a rainy day?",
    "Do you have a favorite quote that inspires you?",
    "If you could change one thing about your past, what would it be and why?",
    "What's the most beautiful natural place you've ever seen?",
    "If you could have a conversation with any animal, which one would you choose and why?",
    "What's the most challenging thing you've ever accomplished academically?",
    "Do you have a favorite memory with a grandparent or elder?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most adventurous thing you've ever eaten?",
    "What's the most interesting historical fact you know?",
    "If you could bring one fictional character to life, who would it be and why?",
    "What's your favorite type of music, and why does it resonate with you?",
    "Have you ever had a life-changing moment or realization?",
    "If you could go back in time and change one decision, what would it be and why?",
    "What's the most significant change you'd like to see in the world?",
    "If you could have any meal prepared for you right now, what would it be?",
    "What's your favorite quote about life?",
]

dirty_truths = [
    "Name 10 body parts that your boyfriend likes to kiss.",
    "Name 10 items you bought but regretted buying and never used.",
    "If you were a boy/girl (of the opposite sex), would you make out with yourself?",
    "Describe the most embarrassing moment of your life.",
    "Have you ever stuck chewing gum under a desk?",
    "Which one do you think is better – tests or essays?",
    "Have you ever eaten a meal by yourself? Where and why?",
    "If you had to go to one class for the rest of your life, what class would you choose it to be?",
    "If you wanted to make out with your guy/girl on campus, where would you do it?",
    "Have you ever gotten into a fistfight on school grounds?",
    "Have you ever fallen asleep while a class was on?",
    "Have you ever been suspended or gotten detention? Why?",
    "If you had the chance, would you sneak a peek in the other gender locker room?",
    "Who is the hottest teacher in school/college?",
    "Have you ever sexted someone you shouldn’t?",
    "Have you ever been publicly humiliated? Explain what happened.",
    "What was the strangest dream you had?",
    "Which celebrity would you like to swap lives with for a month?",
    "Which feature do you get complimented on the most? Do you like it?",
    "Name one thing that you would never do even if you were offered all the money in the world.",
    "Among all the people in the room, which boy would you agree to date?",
    "Among all the people in the room, which boy would you never date?",
    "What is that one characteristic or quality that you would like to change about you?",
    "Have you ever fallen out of love? Did you break up after that?",
    "What is the craziest thing that has happened to you in a public place?",
    "Describe the most annoying experience you had at a mall.",
    "What is the meanest thing you have said to someone?",
    "Have you ever considered cheating on your boyfriend?",
    "Have you ever lied to your boyfriend, saying that you feel sick, to avoid an intimate moment?",
    "What is a rumor or gossip you repeated about someone but found out was incorrect?",
]
dares = [
    "Take an embarrassing selfie and post it as your profile picture",
    "Remove your socks with your teeth",
    "Go next door with a measuring cup and ask for a cup of sugar",
    "Let the group choose an item for you to brush your teeth with",
    "Write your name on the floor with your tongue",
    "Stick a Hot Cheeto in your nose, and leave it there for five minutes",
    "Open your front door and howl like a wolf for 30 seconds",
    "Let the person to your right put duct tape on any part of your body they choose and rip it off",
    "Put a bunch of honey on your nose and coat it with flour",
    "Until the next round, talk super loud, like nobody can hear you",
    "Call your crush",
    "Take a shot of pickle juice",
    "Talk to a pillow like it’s your crush",
    "Pretend you’re a bird and eat cereal off the floor using only your mouth",
    "Make out with your hand",
    "Let someone else style your hair and keep it that way for the rest of the day",
    "Use a brush like you’re talking into a microphone each time you speak",
    "Color one of your front teeth black. (Eyeliner works!)\nPick your friend’s nose",
    "Fake cry",
    "Make repulsive sounds while eating and drinking",
    "Cross your eyes when talking",
    "Talk without closing your mouth",
    "Act like an animal of the group’s choosing",
    "Get into a debate with a wall",
    "Squirt your face with a squirt gun continuously while talking",
    "See how many grapes you can stuff in your mouth",
    "Hiccup in between each word",
    "Burp the alphabet",
    "Draw on your face with permanent marker",
    "Dip your sock-covered feet in the toilet, and don't dry them off for the rest of the game",
    "Eat a spoonful of mustard",
    "Lift up the couch cushions, and if there is anything under them, you need to put it in your mouth for 10 seconds",
    "Spin around 10 times and try to walk straight",
    "Eat a raw egg",
    "Let the group choose three random things from the refrigerator and mix them together. Then you have to eat the mixture",
    "Stand up and do jumping jacks until your next turn",
    "Rub your armpits and then smell your fingers",
    "Dig through the trash and name everything you find",
    "Go on Facebook Live and read the back of a shampoo bottle",
    "Call a 7-Eleven and ask if they’re open",
    "Stand in the backyard and yell at the top of your lungs, “Nooooo! I was adopted!”\nGo outside in the driveway and do the disco without music",
    "Call a car part store and tell them that you need a part for your Model T",
    "Take a selfie with the toilet and post it online",
    "Sniff everyone’s feet and rank them in order of freshest to stinkiest",
    "Call a NY-style pizza place and ask them what the difference is between NY pizza and “real” pizza",
    "Open your front door and loudly sing “Hallelujah!”\nGo outside and pretend you're cutting the grass with an invisible mower",
    "Call a pizza place and ask if they use cruelty-free wheat in their dough",
    "Call your mom and tell her you can't find a girlfriend in a very panicked voice",
    "Wear your underwear over your pants for the rest of the game",
    "Call the library and ask if they carry a dictionary that translates British to American",
    "Send a Snapchat of you pretending to cry because you just found out you were adopted",
    'Go on Facebook and write "How do you spell "facebook"?" as your status',
    "Sniff the armpit of the person next to you, and describe what it smells like to the entire group",
    "Go outside and try to summon the rain",
    'Sing the "Star-Spangled Banner" in a British accent',
    "Take a picture of a tampon and post it on Instagram",
    "Call a random number, and when someone picks up, immediately start singing the national anthem",
    "Call Target and ask them if they deliver popcorn",
    "Call McDonald's and ask if they sell Whoppers",
    "Call a pizza shop and ask if you can return a pizza",
    "Call a car dealership and ask if they have any horse buggies in stock",
    "Change your relationship status on Facebook to \"it's complicated.\"\nCall Macy's and tell them you're interested in buying them",
    "Sing instead of speaking for the next two rounds of the game",
    'Call a random number and sing "Happy Birthday."\nCall a Chinese restaurant and ask if they have sushi',
    "Go outside and pick exactly 40 blades of grass with a pair of tweezers",
    "Eat a whole piece of paper",
    "Fill your mouth with water, and each person in the group must tell the funniest joke they know. If you spit up the water, you have to eat a spoonful of dirt",
    "Tie your hands to your ankles for the rest of the game",
    "Suck your big toe",
    "Eat a mouthful of raw pasta",
    "Dump a bunch of LEGOs on the floor and walk over them with your bare feet",
    "Write a letter to your doctor describing an embarrassing rash you have, and post it on Facebook",
    "Go outside and hug a mailbox until at least three passersby have seen you",
    "Only speak in rhymes for the rest of the game",
    "Soak a shirt in water, put it in the fridge for 20 minutes, and then wear it",
    "Trade clothes with the person next to you",
    "Make a silly face and keep it that way until the next round",
    "Kneel for an hour",
    "Let someone wax your back",
    "Drink water straight from a running faucet for a whole minute",
    'For the rest of the game, do not say "I."\nMake up a rap about koalas',
    "Call a stranger and tell them a secret",
    "Allow someone to pour ice down your shirt and pants",
    "Let each person in the group slap you as hard as they can on your butt",
    "Walk down the street in your underwear",
    "Make your ear touch your shoulder for the rest of the game.",
]

dirty_dares = []
